# Generated by Django 5.2.4 on 2025-07-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderItems.orderitem')),
            ],
        ),
    ]
