# Generated by Django 5.2.3 on 2025-06-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
