# Generated by Django 5.2.4 on 2025-07-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
