# Generated by Django 5.2.4 on 2025-07-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('status', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farmer', models.ForeignKey(limit_choices_to={'type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='users.user')),
            ],
        ),
    ]
