# Generated by Django 5.2.4 on 2025-07-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
        ('orderItems', '0002_remove_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderItems.orderitem'),
        ),
    ]
