# Generated by Django 5.2.4 on 2025-07-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('product_image_url', models.URLField(max_length=500)),
                ('Supplier', models.ForeignKey(limit_choices_to={'type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.user')),
            ],
        ),
    ]
