# Generated by Django 5.2.4 on 2025-07-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Equipments', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'Supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.user'),
        ),
    ]
