# Generated by Django 4.2.23 on 2025-07-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
